# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Jonathan Bonham
title_separator: "-"
subtitle: "CS Student @UAlberta"
description: >- # this means to ignore newlines until "baseurl:"
  A website for my various projects and exploits.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jwillb.net" # the base hostname & protocol for your site, e.g. http://example.com
github_username: jwillb

# Build settings
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-feed
- jekyll-include-cache

collections:
  projects:
    output: true
    permalink: /:collection/:name
  experience:
    output: true
    permalink: /:collection/:name


defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      related: true
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      read_time: true
  # _experience
  - scope:
      path: ""
      type: experience
    values:
      layout: single

include: ["_pages", "_posts", "_projects", "_experience"]
